name: Artifacts workflows
on: push
env:
    artifact-name: animal-say
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download cowsay application
      run: sudo apt-get install cowsay -y


    - name: Create a cowsay file with text
      run: cowsay -f tux "You will face many defeats in life, but never let yourself be defeated." > tuxsay.txt

    - name:  Execute a file to create a quote with elephant
      run: chmod +x ./elephantsay.sh

    - name: Now execute a file
      run: ./elephantsay.sh

    - name: upload the files
      uses: actions/upload-artifact@v4
      with:
        name: $artifact-name
        path: ./*.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download the artifact
      uses: actions/download-artifact@v4
      with:
        name: $artifact-name

    - name: Cat the downloaded artifacts
      run: cat ./*.txt


    - name: Add tuxsay to $artifact-name
      run: cat tuxsay.txt > $artifact-name.txt

    - name: add the elephantsay to $artifact-name
      run: cat elephantsay.txt >> $artifact-name.txt

    - name: upload the artifact
      uses: actions/upload-artifact@v4
      with:
        name: $artifact-name
        path: ./$artifact-name.txt





      

