name: Matrix on workflow
on:
  push:
  workflow_dispatch:

jobs:
  cross-platform:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        images: [nginx,alpine,busybox]
    runs-on: ${{ matrix.os }}
    steps:
      - name: install podman
        run: sudo apt install podman -y
      - name: Fetch the podman version
        run: podman --version > podman-version.txt
      - name: cat the podman-version.txt
        run: cat podman-version.txt
      - name: run podman image in the list ${{ matrix.images }} on ${{ matrix.os }}
        run: podman run ${{ matrix.images }}
