name: Matrix on workflow
on:
  push:
  workflow_dispatch:

jobs:
  cross-platform:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        images: [busybox,alpine]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Fetch the docker version
        run: docker --version > docker-version.txt

      - name: cat the docker-version.txt
        run: cat docker-version.txt

      - name: run docker image in the list ${{ matrix.images }} on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}
