name: Multiple jobs workflow
on: push

jobs:
  build-job-1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay Program
      run: sudo apt install cowsay -y

    - name: Create a dragon txt with custom text 
      run: cowsay -f dragon "Hello This is Multiple jobs Dragon" > Dragon.txt

    - name: sleep for 20 sec
      run: sleep 20

    - name: Upload the Dragon file
      uses: actions/upload-artifact@v4
      with:
        name: my-dragon-file
        path: Dragon.txt


  test-job-2:
    needs: build-job-1
    runs-on: ubuntu-latest
    steps:
    - name: sleep for 10 sec
      run: sleep 10

    - name: Download the artifact
      uses: actions/download-artifact@v4
      with:
        name: my-dragon-file

    - name: Verify if the file is present
      run: ls

  deploy-job-3:
    needs: [build-job-1,test-job-2]
    runs-on: ubuntu-latest
    steps:
    - name: Read the Dragon file.
      run: Cat Dragon.txt

    - name: Download the artifact
      uses: actions/download-artifact@v4
      with:
        name: my-dragon-file

    - name: Verify if the file is present
      run: ls
