name: Test workflow one
on: push
jobs:
  test-job-1:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Welcome Message
      run: echo "My test GitHub Actions Job"

    - name: print the current working Directory
      run: ls

    - name: Read file
      run: cat README.md

    - name: Cowsay Welcome Message in one step
      run: |
        apt install cowsay -y
        cowsay -f gragon "Run for Cover, I Am a Dragon" > Dragon.txt
        cat Dragon.txt