name: Triggered workflow
on: push
#    workflow_dispatch:
#    schedule:
#        - cron: "*/2 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
        group: productions-deploy
        cancel-in-progress: true
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: install cowsay
      run: sudo apt-get install cowsay -y

    - name: Echo cowsay elephant every 1 minute
      run: |
        cowsay -f elephant "Hello World from elephant"
        sleep 60s

