name: Workflow event triggers
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - '!test-branch'
    pull_request:
      types:
        - opened
        - closed
      paths-ignore:
        - README.md
      branches:
        - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: echo Hello World
      run: echo "Hello World"
          